### ISSUE TITLE
Provide a default format upon creation of an assignment

### ISSUE THREAD

**Issue by Airgetfrog** [eJourn-al/eJournal#169]
Ideally we should create assignments with a format including a simple default template with a single textbox

**Comment by Rickyboy320** [comment]
I wonder if this is exactly what we want.

In the case a teacher creates a course, shouldn't they simply be sent to the format editor to start creating the course to their liking? If there already are nodes and templates in place, that could possibly cause confusion. What I would suggest instead is that upon finding an empty format, a message saying "The teacher has not finished setting this course up yet." should appear on the page, or something similar.

Having students be able to post entries on a 'dummy' format, would cause the entries to persist forever, even once the format was edited. This could cause even more confusion if a student accidentally views the assignment before it was properly set up.

I'm suggesting changing this issue from providing a default to providing helpful messages and improving the general flow of the website upon course / assignment creation, to automatically require the configuration of the format, and if this is not the case (the student views the assignment before it was set up) they would simply be shown a message rather than the blank page we have now.

**Comment by engelhamer** [comment]
On my current branch I have implemented the functionality to send a teacher directly into the format editor upon creation of an assignment. A teacher could set up his very own complex format there, but might as well simply want a place for his students to post some text to their own liking. The latter will probably be the case most of the time. To speed things up for teachers, it is therefore useful to provide a default format (consisting of one deadline that contains the maximum amount of points for the assignment, as well as a one-field rich text template).

**Comment by engelhamer** [comment]
#278 will additionally provide instructions on how to use the format editor, so a teacher should be able to get rid of the default format right away if they want to.

**Comment by engelhamer** [comment]
I just realized: Without a default format it would not be possible to do a tour all that easily, since e.g. template cards will not be there.
