### ISSUE TITLE
More fine grained permissions with verbose names

### ISSUE THREAD

**Issue by Rickyboy320** [eJourn-al/eJournal#259]
Now that certain permissions are starting to require more and more components, certain names no longer properly reflect the elements they affect. Permissions such as can_view_assignment_participants does not just concern viewing participants, but also their journal, their files, and probably more. In order to preserve integrity for permissions, we should rename problematic permissions to more descriptive counterparts.

The offending permissions will need to be identified, and a better name for them should be chosen on a case-by-case basis.

**Comment by engelhamer** [comment]
In addition to this, we should think about some sort of structure in which
certain permissions are chained. For example: The ability to grade shall
only be granted tot users that can view course participants.

Op 18 aug. 2018 12:05 schreef "Rick" <notifications@github.com>:

Now that certain permissions are starting to require more and more
components, certain names no longer properly reflect the elements they
affect. Permissions such as can_view_assignment_participants does not just
concern viewing participants, but also their journal, their files, and
probably more. In order to preserve integrity for permissions, we should
rename problematic permissions to more descriptive counterparts.

The offending permissions will need to be identified, and a better name for
them should be chosen on a case-by-case basis.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eJourn-al/eJournal/issues/259>, or mute the thread
