### ISSUE TITLE
Visual indication that an assignment/course is linked via LTI

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#357]
# Feature request

## Description
Add a visual indication that an assignment/course is linked via LTI.
![image](https://user-images.githubusercontent.com/11822478/45646604-18f70b80-bac4-11e8-9f64-35725de05367.png)
A link icon on the top left of each linked item would be nice

**Comment by engelhamer** [comment]
Preferrably a label like so. Please check this for individual assignments themselves since it is perfectly possible that they are not linked via LTI but a course is.

![45646604-18f70b80-bac4-11e8-9f64-35725de05367](https://user-images.githubusercontent.com/39912581/45646984-0e894180-bac5-11e8-97f8-aca31db65be0.png)
