### ISSUE TITLE
Excessive 'Token expired' toasts

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#585]
**Describe the bug**
If a user was previously logged in but their token has expired, they will be redirected to a login screen when they try to visit a page. Upon arrival, two (sometimes more) toasts stating that their token has expired (or might be invalid) pop up.

**To Reproduce**
1. Log in
2. Wait for the token to expire
3. Visit a page
4. Observe an abundance of toasts

**Expected behavior**
Only one toast.

**Comment by mjvkeulen** [comment]
This occurs because loading a page triggers multiple api requests, each of which will first try to refresh the token in localstorage. As the token is indeed invalid, all refresh attempts will fail, each in turn toasting their respective error message. Which for this scenario is the same message of the token being invalid. This mechanism is flawed in its design, as when a single request fails due to the token being invalid all other authenticated request are guaranteed to fail anyway.

Ideally, upon failing a request due to an invalid token, all other invalid requests (by token) should be queued until the first request has successfully refreshed the token and then be tried again.
