### ISSUE TITLE
Images cause rich text fields to partially hide content

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#782]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11822478/68026440-0895f600-fcb0-11e9-8d24-d9281ce9146a.png)

The image is not fully shown as the iframe cuts it off. This is most likely a loading issue where the hight of the images is not yet properly set.

**Comment by engelhamer** [comment]
Interesting one: the iframe onLoad should trigger a resize, but from some testing it looks as if the images are not included here. Additional downside is that in this context the iframe does not support javascript, since we fill it with user-generated content. Otherwise it would be possible to add an onload to all image tags.

**Comment by engelhamer** [comment]
This can be generalised to all rich text fields (iframes), not just entries.

**Comment by engelhamer** [comment]
Fixed in #799.
